# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

services:
  map-saver:
    image: husarion/nav2-map-server:humble-1.1.5-20230204-stable
    network_mode: host
    ipc: host
    volumes:
      - ./maps:/maps
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: bash -c "while true; do ros2 run nav2_map_server map_saver_cli --free 0.15 --fmt png -f /maps/map; sleep 5; done"

  rviz:
    image: husarion/rviz2:galactic-8.5.2-20230204-stable
    container_name: rviz
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

  joy2twist:
    image: husarion/joy2twist:humble-1.0.0-20230204-stable
    network_mode: host
    ipc: host
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml

