services:

  rviz:
    image: husarion/rviz2:humble-22-12-20
    runtime: nvidia
    container_name: rviz
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
      - DISPLAY=${DISPLAY:?err}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

  rosbot-xl:
    image: husarion/webots:galactic
    runtime: nvidia
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
      - DISPLAY=${DISPLAY:?err}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: ros2 launch webots_ros2_husarion robot_launch.py robot_name:="rosbot_xl"

  mapping:
    image: husarion/slam-toolbox:humble-22-12-07
    network_mode: host
    ipc: host
    volumes:
      - ./config/slam_toolbox_params_webots.yaml:/slam_params.yaml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=True

  map-saver:
    image: husarion/nav2-map-server:humble-22-12-07
    network_mode: host
    ipc: host
    volumes:
      - ./maps:/maps
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: bash -c "while true; do ros2 run nav2_map_server map_saver_cli --free 0.15 --fmt png -f /maps/map; sleep 5; done"