services:

  rosbot:
    image: husarion/rosbot-xl:humble-0.10.0-20240216
    network_mode: host
    ipc: host
    restart: unless-stopped
    # devices:
    #   - /dev/ttyUSBDB # just for firmware flashing
    #   - /dev/bus/usb/ # just for firmware flashing
    ports:
      - 192.168.77.2:8888:8888/udp
    command: >
      ros2 launch /husarion_utils/rosbot.launch.py
        mecanum:=${MECANUM:-True}
        include_camera_mount:=True
        healthcheck:=False

  rplidar:
    image: husarion/rplidar:humble-1.0.1-20230206-stable
    network_mode: host
    ipc: host
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  mapping:
    image: husarion/slam-toolbox:humble-2.6.4-20230204-stable
    network_mode: host
    ipc: host
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}
